# Generated by Django 5.2.16 on 2026-08-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('cantidad_puntos', models.IntegerField()),
                ('imagenes_relacionadas', models.ImageField(blank=True, null=True, upload_to='imagenes_tareas/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='academico.curso')),
            ],
        ),
    ]
