# Generated by Django 5.2.16 on 2026-08-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='Fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(default='Vencida', max_length=20),
        ),
    ]
