# Generated by Django 5.2.16 on 2026-08-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_tarea_fecha_entrega_tarea_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
    ]
