# Generated by Django 5.2.16 on 2026-08-09 15:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_remove_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=tinymce.models.HTMLField(),
        ),
    ]
