# Generated by Django 5.2.16 on 2026-08-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_alter_tarea_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='imagenes_relacionadas',
        ),
    ]
