# Generated by Django 5.2.16 on 2026-08-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_remove_tarea_imagenes_relacionadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_tareas/')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='evaluaciones.tarea')),
            ],
        ),
    ]
