# Generated by Django 5.2.16 on 2026-08-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_archivotarea'),
        ('usuarios', '0002_remove_usuario_username_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_archivo', models.FileField(blank=True, null=True, upload_to='entregas_estudiantes/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='usuarios.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='evaluaciones.tarea')),
            ],
        ),
    ]
