# Generated by Django 5.2.16 on 2026-08-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivotarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='evaluaciones.tarea'),
        ),
        migrations.CreateModel(
            name='ArchivoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregas_estudiantes/multiples/')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='evaluaciones.calificacion')),
            ],
        ),
    ]
