# Generated by Django 5.2.16 on 2026-08-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0008_alter_archivotarea_tarea_archivoentrega'),
        ('usuarios', '0003_estudiante_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivotarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='evaluaciones.tarea'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('tarea', 'estudiante')},
        ),
    ]
