# Generated by Django 5.2.16 on 2026-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_username_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/'),
        ),
    ]
