# Generated by Django 5.2.16 on 2026-08-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_estudiante_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='maestros/'),
        ),
    ]
